### ISSUE TITLE
CLI DB sync tool for shlokam.org and valmiki 

### ISSUE THREAD

**Issue by ks0m1c** [ve1ld/vyasa#37]
Implemented in Livebook not ported to the db clause on the CLI for Shlokam

_Originally posted by @KosmonautX in https://github.com/ve1ld/vyasa/pull/24#discussion_r1487623724_

**Comment by rtshkmr** [comment]
admin view was added, will close this issue because it lacks verbosity and scope. 

this may be added as a separate issue in the future, with more context to it

let me know if i should revive this issue @ks0m1c
