### ISSUE TITLE
[Operation]: Lexical Engine 

### ISSUE THREAD

**Issue by ks0m1c** [ve1ld/vyasa#6]
### Present Context

Where we collectively investigate and interrogate the problem space and iteratively scope our approach.

Breakdown to landmarks that communicate shared context we are working towards through 2-tiered task list, CRUD list elements as development unfolds.

Strike the scope of code that reveals the most about the problem/solution FIRST not necessarily the easiest or hardest parts

- [ ] Lexicon
    - [ ]  Find key sources of lexical data
    - [ ]  Cluster and group together by source
  
- [ ] Coverage Test
    - [ ]  Check coverage for current corpus
    - [ ]  Scrape and reverse lookup leftovers

---
### Groundwork

Introduce us to the problem space. Write out what you already know about the terrain you are the recce commander enriching us with details beyond the fog of war.

Where have you tried applying and encountered difficulties?

How have others attempted to scale or explore these challenges? 

(Embed internal & external links to related or possible  paths of exploration, stackoverflow, documentation, github etc)

Who should be notified?

Emphasis on previous or current practice to discover what is ugly, missing, or unnecessary.
```
https://sanskritdictionary.com/?q=wonder&lang=en&action=Search

```
---
### Reflection

Where the eternal wheel returns back to practice and what we finally implemented is to be outlined. You are the historian or archivist bringing clarity to future-yous and us about your foray.

Emphasis on approaching timeless solutions for well-defined problem space through distillation by decanting that which is un-needed and abstracting that which is essential to approaching the problem space. 

Add any reflections and internal links to future potential and blindsides.

```
INPUT UR ANSWER HERE
```

**Comment by rtshkmr** [comment]
@ks0m1c possible to close this? 

I feel that this issue is too abstract in its content, we should keep our issues focused on what needs to be implemented, else shift discussions to `discussions`

**Comment by rtshkmr** [comment]
closing this, I notice that #29 has already been created that defines what's needed there
