### ISSUE TITLE
[Operation]: Clearinghouse

### ISSUE THREAD

**Issue by ks0m1c** [ve1ld/vyasa#68]
### Present Context
To be cleared, clarified or culled
```
- Admin
 - License (GPL v3)
  - AppSignal - apply for sponsorship: https://www.appsignal.com/plans
 -  Separate bug tickets from corpus requests and feature requrests
  - possible to send cookie-based payload to the redirection to github-based bug report form.
  - discussion posts can be interfaced using graphql -- might make sense for corpus requests.

- Rich Media Session

- [ ] API should use image-gen img
- [ ] Attributions to be added to the medium's meta
- [ ] "Library" / "Bridge" selection of audio from multiple audio


Content QA and legwork
- [ ]  Gita Rest of chaps (2-18) coming soon

Misc
- [ ] screen listener for resize changes.

```
---

</details>

### Groundwork

<details>
<summary> Helping words...</summary>

Introduce us to the problem space. Write out what you already know about the terrain you are the recce commander enriching us with details beyond the fog of war.

Where have you tried applying and encountered difficulties?

How have others attempted to scale or explore these challenges? 

(Embed internal & external links to related or possible  paths of exploration, stackoverflow, documentation, github etc)

Who should be notified?

Emphasis on previous or current practice to discover what is ugly, missing, or unnecessary.
```
INPUT UR ANSWER HERE
```
---

</details>

### Reflection

<details>
<summary> Helping words...</summary>
Where the eternal wheel returns back to practice and what we finally implemented is to be outlined. You are the historian or archivist bringing clarity to future-yous and us about your foray.

Emphasis on approaching timeless solutions for well-defined problem space through distillation by decanting that which is un-needed and abstracting that which is essential to approaching the problem space. 

Add any reflections and internal links to future potential and blindsides.

```
INPUT UR ANSWER HERE
```

</details>

**Comment by rtshkmr** [comment]
this issue is to be split into multiple other issues
